= REST API Guide
김영재;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `DELETE`
| 리소스를 삭제 할 떄 사용

|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `204 No Content`
| 요청 리소스가 정상적으로 삭제 됨.

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[resource-create-groupCode]]
=== 그룹코드 등록하기.

`POST` 요청을 사용해서 그룹코드를 등록 할 수 있다.

operation::create-groupCode[snippets='request-fields,curl-request,http-request,request-headers,http-response,response-headers,response-fields,response-body,links']

[[resource-create-commonncode]]
=== 문자 조회

`GET` 요청을 사용해서 공통코드를 등록 할 수 있다.

operation::create-commonncode[snippets='request-fields,curl-request,http-request,request-headers,http-response,response-headers,response-fields,response-body,links']

[[resource-get-groupCode]]
== 그룹코드 정보 가져오기.

`GET` 요청을 사용해서 그룹코드를 가져 올 수 있다.
공통코드는 따로가져올 수 있다.

operation::get-groupCode[snippets='path-parameters,curl-request,http-request,http-response,response-headers,response-fields,response-body,links']

[[resource-delete-commoncode]]
== 공통코드 정보 지우기.

`DELETE` 요청을 사용해서 공통코드를 삭제 할 수 있다.

operation::delete-commoncode[snippets='path-parameters,curl-request,http-request,http-response']

[[resource-request-error_1]]
== 그룹코드 생성 시 요청 에러

예를 들어, 잘못된 요청으로 그룹코드 생성 요청 시 다음과 같은 `400 Bad Request` 응답을 받는다.

operation::request-error_1[snippets='request-fields,curl-request,http-request,request-headers,http-response,response-headers,response-fields,response-body']


[[resource-request-error_2]]
== 공통코드 생성 시 요청 에러

예를 들어, 잘못된 요청으로 그룹코드 생성 요청 시 다음과 같은 `400 Bad Request` 응답을 받는다.

operation::request-error_2[snippets='request-fields,curl-request,http-request,request-headers,http-response,response-headers,response-fields,response-body']

[[resource-mainapi-check]]
== 공통코드 유효성 체크 API

해당 API의 메인 기능이다.

operation::mainAPI-check[snippets='path-parameters,curl-request,http-request,request-headers,http-response,response-headers,response-fields,response-body,links']


[[resource-mainapi-check-error-1]]
== 공통코드 유효성 체크 API 에러-1

공통 코드 사용 여부가 false이면 `400 Bad Request` 응답을 받는다.

operation::mainAPI-check-error-1[snippets='path-parameters,curl-request,http-request,request-headers,http-response,response-headers,response-fields,response-body']


[[resource-mainapi-check-error-2]]
== 공통코드 유효성 체크 API 에러-2

유효 시작시간이 현재 일자보다 이후이면 `400 Bad Request` 응답을 받는다.

operation::mainAPI-check-error-2[snippets='path-parameters,curl-request,http-request,request-headers,http-response,response-headers,response-fields,response-body']


[[resource-mainapi-check-error-2]]
== 공통코드 유효성 체크 API 에러-3

유효 종료시간이 현재 일자보다 이전이면 `400 Bad Request` 응답을 받는다.

operation::mainAPI-check-error-3[snippets='path-parameters,curl-request,http-request,request-headers,http-response,response-headers,response-fields,response-body']