spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: 'create-drop'
        format_sql: true
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace